//===================== Men wears ============================
const MenProduct = [
    {
        "image5": "https://assets.ajio.com/medias/sys_master/root/20231122/BG7w/655d2da1afa4cf41f59741c8/-473Wx593H-466816474-pink-MODEL.jpg",
        "image1": "https://images.meesho.com/images/products/291367680/kfsgy_512.webp",
        "image2": "https://images.meesho.com/images/products/291367680/fni1a_512.webp",
        "image3": "https://images.meesho.com/images/products/291367690/s8qwb_512.webp",
        "image4": "https://images.meesho.com/images/products/291367690/lux0k_512.webp",
        "name": "shirt",
        "brand": "MANYAVAR",
        "details": "Men Woven Regular Fit Nehru jacket",
        "price": 3999,
        "MRP": 4999,
        "offer": "25% off",
        "color": "green, whie",
        "size": "34,34",
        "origin": "india",
        "id": 31
    },
    {
        "image5": "https://assets.ajio.com/medias/sys_master/root/20230201/F83u/63da41a3aeb269c651085959/-473Wx593H-443005598-olive-MODEL.jpg",
        "image1": "https://images.meesho.com/images/products/363341259/w33mp_512.webp",
        "image2": "https://images.meesho.com/images/products/363341259/lpgn6_512.webp",
        "image3": "https://images.meesho.com/images/products/363341259/sruhv_512.webp",
        "image4": "https://images.meesho.com/images/products/363341259/0ot6x_512.webp",
        "name": "shirt",
        "brand": "nikky",
        "details": "Slim Fit Shirt with Patch Pocket",
        "price": 390,
        "MRP": 1200,
        "offer": "70% off",
        "color": "multicolor",
        "size": "34,34",
        "id": 32
    },
    {
        "image5": "https://images.meesho.com/images/products/393335348/nf4rp_512.webp",
        "image1": "https://images.meesho.com/images/products/217904204/iz8wr_512.webp",
        "image2": "https://images.meesho.com/images/products/217904204/azp9v_512.webp",
        "image3": "https://images.meesho.com/images/products/217904204/y7dhd_512.webp",
        "image4": "https://images.meesho.com/images/products/217904204/kac3t_512.webp",
        "name": "Jogger Trackpant",
        "brand": "white shirt",
        "details": " white shirt Fabric : Cotton Linen Sleeve Length : Long Sleeves",
        "price": 800,
        "MRP": 1300,
        "offer": "65% off",
        "color": "green, white",
        "size": "34,34",
        "id": 33
    },
    {
        "image5": "https://images.meesho.com/images/products/366583107/92f6r_512.webp",
        "image1": "https://rukminim2.flixcart.com/image/832/832/xif0q/trouser/y/q/n/36-single-pista-combraided-original-imagybg2u9e2bmat.jpeg?q=70&crop=false",
        "image2": "https://rukminim2.flixcart.com/image/832/832/xif0q/trouser/b/f/c/36-single-pista-combraided-original-imagybg2hvnga5sb.jpeg?q=70&crop=false",
        "image3": "https://rukminim2.flixcart.com/image/832/832/xif0q/trouser/z/h/s/36-single-pista-combraided-original-imagybg2zv6emapw.jpeg?q=70&crop=false",
        "image4": "https://rukminim2.flixcart.com/image/832/832/xif0q/trouser/i/r/p/36-single-pista-combraided-original-imagybg27zjcvwyz.jpeg?q=70&crop=false",
        "name": "Trousers",
        "brand": "shirt",
        "details": "Men's black shirt ",
        "price": 400,
        "MRP": 600,
        "offer": "85% off",
        "color": "green, white",
        "size": "34,34",
        "id": 34
    },
    {
        "image5": "https://images.meesho.com/images/products/290280429/vdqgw_512.webp",
        "image1": "https://images.meesho.com/images/products/147644618/evjzm_512.webp",
        "image2": "https://images.meesho.com/images/products/147644618/dnzey_512.webp",
        "image3": "https://images.meesho.com/images/products/147644618/ztrle_512.webp",
        "image4": "https://images.meesho.com/images/products/147644618/yfnev_512.webp",
        "name": "Men Jeans",
        "brand": " Denim",
        "details": " Men Denim Black Jeans manufaturing jeans in awesome quality",
        "price": 600,
        "MRP": 1100,
        "offer": "45% off",
        "color": "green, whie",
        "size": "34,34",
        "id": 35
    },
    {
        "image5": "https://images.meesho.com/images/products/394196769/5b23s_512.webp",
        "image2": "https://assets.ajio.com/medias/sys_master/root/20240301/RYfT/65e1c26e05ac7d77bb8f8323/-473Wx593H-443002614-jetblack-MODEL2.jpg",
        "image1": "https://assets.ajio.com/medias/sys_master/root/20240301/kqov/65e1c4c605ac7d77bb8f8fa3/-473Wx593H-443002614-jetblack-MODEL.jpg",
        "image3": "https://assets.ajio.com/medias/sys_master/root/20240301/2Dcr/65e1c3c416fd2c6e6a33e067/-473Wx593H-443002614-jetblack-MODEL6.jpg",
        "image4": "https://assets.ajio.com/medias/sys_master/root/20240301/2Dcr/65e1c3c416fd2c6e6a33e067/-473Wx593H-443002614-jetblack-MODEL6.jpg",
        "name": " Jeans",
        "brand": "Denim",
        "details": "Jeans for men Fabric Denim Pattern : Solid",
        "price": 800,
        "MRP": 1800,
        "offer": "85% off",
        "color": "green, whie",
        "size": "34",
        "id": 36
    },

    {
        "image5": "https://assets.ajio.com/medias/sys_master/root/20230915/rida/650447bfddf7791519db713d/-473Wx593H-443017556-maroon-MODEL.jpg",
        "image1": "https://assets.ajio.com/medias/sys_master/root/20230814/kHUO/64da1ef0eebac147fcc774e8/-473Wx593H-466454740-yellow-MODEL5.jpg",
        "image2": "https://assets.ajio.com/medias/sys_master/root/20230814/kHUO/64da1ef0eebac147fcc774e8/-473Wx593H-466454740-yellow-MODEL5.jpg",
        "image3": "https://assets.ajio.com/medias/sys_master/root/20230814/kHUO/64da1ef0eebac147fcc774e8/-473Wx593H-466454740-yellow-MODEL5.jpg",
        "image4": "https://assets.ajio.com/medias/sys_master/root/20230814/kHUO/64da1ef0eebac147fcc774e8/-473Wx593H-466454740-yellow-MODEL5.jpg",
        "name": "Long Kurta",
        "brand": "JOMPERS",
        "details": "Colourblock Regular Fit Sweatshirt",
        "price": 450 ,
        "MRP": 1499,
        "offer": "70% off",
        "color": "green, whie",
        "size": "34,34",
        "id": 37
    },
    {
        "image5": "https://rukminim2.flixcart.com/image/832/832/xif0q/trouser/j/n/m/36-el-p-cot-el-cielo-original-imagtha4rgrqmtu3.jpeg?q=70&crop=false",
        "image1": "https://assets.ajio.com/medias/sys_master/root/20220328/Rawz/6241ca8aaeb26921affa486e/-473Wx593H-464075356-white-MODEL.jpg",
        "image2": "https://assets.ajio.com/medias/sys_master/root/20220328/38LM/6241ca8aaeb26921affa480a/-473Wx593H-464075356-white-MODEL3.jpg",
        "image3": "https://assets.ajio.com/medias/sys_master/root/20220328/38LM/6241ca8aaeb26921affa480a/-473Wx593H-464075356-white-MODEL3.jpg",
        "image4": "https://assets.ajio.com/medias/sys_master/root/20231219/QyeH/6580c5e7ddf7791519d7b2eb/-473Wx593H-464075356-multi-MODEL3.jpg",
        "name": "Kurta with Pyjama Set",
        "brand": "KISAH",
        "details": "Men Regular Fit Grey Cotton Blend Trousers",
        "price": 4619,
        "MRP": 10998,
        "offer": "58% off",
        "color": "green, whie",
        "size": "34,34",
        "id": 38
    },
    {
        "image5": "https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/d/a/u/xxl-aut-formal-metronaut-original-imagwmj5gupusyza.jpeg?q=70&crop=false",
        "image1": "https://assets.ajio.com/medias/sys_master/root/20230629/b0KI/649d26c4eebac147fc3cbae8/-473Wx593H-466123407-pink-MODEL.jpg",
        "image2": "https://assets.ajio.com/medias/sys_master/root/20230629/fGB2/649d26caeebac147fc3cbb1c/-473Wx593H-466123407-pink-MODEL3.jpg",
        "image3": "https://assets.ajio.com/medias/sys_master/root/20230629/LuUl/649d26caeebac147fc3cbb1d/-473Wx593H-466123407-pink-MODEL5.jpg",
        "image4": "https://assets.ajio.com/medias/sys_master/root/20230629/wXTb/649d26caeebac147fc3cbb1e/-473Wx593H-466123407-pink-MODEL6.jpg",
        "name": "Crew-Neck T-Shirt",
        "brand": "formal shirt ",
        "details": "Men Regular Fit Solid Formal Shirt",
        "price": 390,
        "MRP": 1299,
        "offer": "80% off",
        "color": "green, whie",
        "size": "34,34",
        "id": 39
    },
    {
        "image5": "https://assets.ajio.com/medias/sys_master/root/20230818/2eRV/64df8883ddf77915195286c5/-1117Wx1400H-443021148-navy-MODEL.jpg",
        "image1": "https://assets.ajio.com/medias/sys_master/root/20231009/zQTp/65240373ddf77915192c18aa/-473Wx593H-466687925-black-MODEL.jpg",
        "image2": "https://assets.ajio.com/medias/sys_master/root/20231009/A9k5/65240372ddf77915192c1838/-473Wx593H-466687925-black-MODEL3.jpg",
        "image3": "https://assets.ajio.com/medias/sys_master/root/20231009/8jTq/65240372ddf77915192c183d/-473Wx593H-466687925-black-MODEL6.jpg",
        "image4": "https://assets.ajio.com/medias/sys_master/root/20231009/8jTq/65240372ddf77915192c183d/-473Wx593H-466687925-black-MODEL6.jpg",
        "name": "Nehru Jacket",
        "brand": "Blazer",
        "details": "Heathered Slim Fit Single-Breasted Blazer",
        "price": 1200,
        "MRP": 3999,
        "offer": "70% off",
        "color": "green, whie",
        "size": "34,34",
        "id": 40
    },
    {
        "image5": "https://assets.ajio.com/medias/sys_master/root/20240119/GM44/65a9a59716fd2c6e6ab1d059/-473Wx593H-466994285-multi-MODEL2.jpg",
        "image1": "https://assets.ajio.com/medias/sys_master/root/20230628/spRg/649be403eebac147fc2327be/-473Wx593H-465806945-blue-MODEL3.jpg",
        "image2": "https://assets.ajio.com/medias/sys_master/root/20230628/Gd3B/649be403eebac147fc2327c2/-473Wx593H-465806945-blue-MODEL6.jpg",
        "image3": "https://assets.ajio.com/medias/sys_master/root/20230628/Gd3B/649be403eebac147fc2327c2/-473Wx593H-465806945-blue-MODEL6.jpg",
        "image4": "https://assets.ajio.com/medias/sys_master/root/20230628/Gd3B/649be403eebac147fc2327c2/-473Wx593H-465806945-blue-MODEL6.jpg",
        "name": "T-Shirt with Shorts",
        "brand": "KISAH",
        "details": "Men Paisley Woven Regular Fit Sherwani with Kurta & Dhoti Pants",
        "price": " 9299",
        "MRP": "18598",
        "offer": "50% off",
        "color": "green, whie",
        "size": "34,34",
        "id": 41
    },
    {
        "image5": "https://rukminim2.flixcart.com/image/416/416/xif0q/shirt/e/u/m/xxl-1500-combraided-original-imagyeuqtdghn4bu.jpeg?q=70&crop=false",
        "image1": "https://assets.ajio.com/medias/sys_master/root/20230629/3sOV/649cef87a9b42d15c91ffd42/-473Wx593H-466070858-black-MODEL.jpg",
        "image2": "https://assets.ajio.com/medias/sys_master/root/20230629/G5HO/649cef8da9b42d15c91ffd74/-473Wx593H-466070858-black-MODEL4.jpg",
        "image3": "https://assets.ajio.com/medias/sys_master/root/20230629/C214/649cef8da9b42d15c91ffd76/-473Wx593H-466070858-black-MODEL6.jpg",
        "image4": "https://assets.ajio.com/medias/sys_master/root/20230629/C214/649cef8da9b42d15c91ffd76/-473Wx593H-466070858-black-MODEL6.jpg",
        "name": "Closure Jacket ",
        "brand": "VOXATI",
        "details": "Slim-Fit Button-Closure Jacket with Flap Pockets",
        "price": 9299,
        "MRP": "18598",
        "offer": "50% off",
        "color": "green, whie",
        "size": "34,34",
        "id": 42
    },
    {
        "image1": "https://assets.ajio.com/medias/sys_master/root/20230624/e4ea/649663cfeebac147fcf20d64/-473Wx593H-465324816-tan-MODEL.jpg",
        "image2": "https://assets.ajio.com/medias/sys_master/root/20230624/yOBx/649663d5eebac147fcf20dc8/-473Wx593H-465324816-tan-MODEL6.jpg",
        "image3": "https://assets.ajio.com/medias/sys_master/root/20230624/yOBx/649663d5eebac147fcf20dc8/-473Wx593H-465324816-tan-MODEL6.jpg",
        "image4": "https://assets.ajio.com/medias/sys_master/root/20230624/oaK4/649663d5eebac147fcf20dc3/-473Wx593H-465324816-tan-MODEL7.jpg",
        "name": "Zip-Front Bomber Jacket",
        "brand": "Winterwear",
        "detail": "Wear this stylish Suede jacket from the house of Campus Sutra. The Suede jacket is comfortable to wear as the fabrics are light on the skin. Using stellar quality solvents,",
        "details": "Long Sleeve : Winter Wear : Solid Jacket : Smoth Jacket : Casual Wear : Western ",
        "price": 1750,
        "MRP": 3499,
        "offer": "50% OFF",
        "color": "Brown",
        "size": 'L',
        "origin":"india",
        "color": "green, whie",
        "size": "34,34",
        "id": 43
    },
    {
        "image1": "https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/s/v/3/l-nvk-4444-nivick-original-imags6frqegpxe7q.jpeg?q=70&crop=false",
        "image2": "https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/y/y/i/l-nvk-4444-nivick-original-imags6frvhhc3vy4.jpeg?q=70&crop=false",
        "image3": "https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/w/u/u/l-nvk-4444-nivick-original-imags6fr669gcnbw.jpeg?q=70&crop=false",
        "image4": "https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/z/p/a/l-nvk-4444-nivick-original-imags6frasenz7w3.jpeg?q=70&crop=false",
        "name": "Formal Shirt",
        "brand": "NIVICK",
        "detail":"Closure: Button Fit :Slim Fabric Cotton Blend Sleeve Full Sleeve Patter Solid  Fabric Care Regular Machine Wash, Hand wash",   
        "details": "Men Slim Fit Solid Spread Collar Formal Shirt",
        "price": 500,
        "MRP":800,
        "color": " Blue",
        "size": 'M, L, S, XL',
        "origin":"india",
        "offer": "63% OFF",
        "color": "green, whie",
        "size": "34,34",
        "id": 44
    },
    {
        "image1": "https://assets.ajio.com/medias/sys_master/root/20230609/bH7P/6483513442f9e729d7357438/-473Wx593H-443005012-ltblue-MODEL.jpg",
        "image2": "https://assets.ajio.com/medias/sys_master/root/20230609/PppO/64833d13d55b7d0c635dd9bc/-473Wx593H-443005012-ltblue-MODEL4.jpg",
        "image3": "https://assets.ajio.com/medias/sys_master/root/20230609/BwZU/64834bb642f9e729d735545d/-473Wx593H-443005012-ltblue-MODEL8.jpg",
        "image4": "https://assets.ajio.com/medias/sys_master/root/20230609/BwZU/64834bb642f9e729d735545d/-473Wx593H-443005012-ltblue-MODEL8.jpg",
        "name": "Denim Jacket",
        "brand": "LEE COOPER ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "LEE COOPER Denim Jacket",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 45
    }
]

//id=46-57
const MenProduct1 = [
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 105
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 106
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 107
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 108
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 109
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 110
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 111
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 112
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 113
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 114
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 115
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 116
    },
]
//id=58-69
const MenProduct2 = [
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 105
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 106
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 107
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 108
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 109
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 110
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 111
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 112
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 113
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 114
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 115
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 116
    },
]

// id=70-81
const MenProduct3 = [
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 105
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 106
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 107
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 108
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 109
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 110
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 111
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 112
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 113
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 114
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 115
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 116
    },
]
// id=82-93
const MenProduct4 = [
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 105
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 106
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 107
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 108
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 109
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 110
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 111
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 112
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 113
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 114
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 115
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 116
    },
]

// id=93-105
const MenProduct5 = [
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 105
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 106
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 107
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 108
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 109
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 110
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 111
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 112
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 113
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 114
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 115
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 116
    },
]

// ============================ Women wears ==================
// id=105-117
const WomenProduct1 = [
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 105
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 106
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 107
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 108
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 109
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 110
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 111
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 112
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 113
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 114
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 115
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 116
    },
]

// id=117-129
const WomenProduct2 = [
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 105
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 106
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 107
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 108
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 109
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 110
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 111
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 112
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 113
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 114
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 115
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 116
    },
]
// id=130-141
const WomenProduct3 = [
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 105
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 106
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 107
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 108
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 109
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 110
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 111
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 112
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 113
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 114
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 115
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 116
    },
]
// id=142-153
const WomenProduct4 = [
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 105
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 106
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 107
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 108
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 109
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 110
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 111
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 112
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 113
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 114
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 115
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 116
    },
]
// id=153-165
const WomenProduct5 = [
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 105
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 106
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 107
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 108
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 109
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 110
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 111
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 112
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 113
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 114
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 115
    },
    {
        "image1": "",
        "image2": "",
        "image3": "",
        "image4": "",
        "name": "Lehenga Choli",
        "brand": "PURVAJA ",
        "detail":"Occasion Wedding & Festive Lehenga Fabric Cotton Blend Type Lehenga Choli Dupatta Fabric Art Silk Neck Sweetheart Neck Sleeve Short Sleeve",
        "details": "Solid, Embellished Semi Stitched Lehenga Choli  (Black)",
        "price": 898,
        "MRP": 6999,
        "offer": "87% OFF",
        "color": "Black",
        "size": "34",
        "origin":"india",
        "id": 116
    },
]






export {MenProduct,MenProduct1,MenProduct2, MenProduct3,MenProduct4, MenProduct5, WomenProduct1, WomenProduct2, WomenProduct3,WomenProduct4,WomenProduct5 };
